# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  var1: value1

trigger:
  batch: true
  branches:
    include:
      - master/*
    exclude:
      - develop/*
  paths:
    exclude:
      - README.md

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'build'
    jobs:
      - job: 'build job'
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'package'
